### ISSUE TITLE
Checkout error - start_checkout(session)

### ISSUE THREAD

**Issue by Kylian-Mallet** [frankied003/DigiBot-V2#3]
Hi, I have a problem with the checkout :

`Traceback (most recent call last):
  File "main.py", line 298, in <module>
    start_checkout(session)
  File "main.py", line 243, in start_checkout
    totalPrice = bs.find('input', {'name': 'checkout[total_price]'})['value']
TypeError: 'NoneType' object is not subscriptable`

If you can help me it's cool, have a nice day !

**Comment by AlismVY** [comment]
Maybe I can help you
